config/routes.rb
Rails.application.routes.draw do
  resources :correspondence, only: %i[new create]

  resources :feedback, only: %i[new create], path: "give-feedback", path_names: { new: "" }
  get "/give-feedback" => "feedback#new", as: "feedback"

  get "/cookies/:consent", to: "cookies#update"
  resource :cookies, only: %i[show update]

  get "/correspondence" => "correspondence#topic"
  get "/correspondence/topic" => "correspondence#topic"
  get "/correspondence/search" => "correspondence#search"
  get "/correspondence/t_and_c" => "correspondence#t_and_c"
  get "/correspondence/authenticate/:uuid" => "correspondence#authenticate", as: "correspondence_authentication"
  get "/correspondence/confirmation/:uuid" => "correspondence#confirmation", as: "correspondence_confirmation"

  get "/accessibility" => "pages#accessibility"

  get "ping", to: "heartbeat#ping", format: :json
  get "healthcheck", to: "heartbeat#healthcheck", as: "healthcheck", format: :json

  get "/404", to: "errors#not_found"
  get "/500", to: "errors#internal_error"

  root to: "correspondence#start"
end

app/models/correspondence.rb
# == Schema Information
#
# Table name: correspondence
#
#  id               :integer          not null, primary key
#  content          :jsonb
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  uuid             :string
#  authenticated_at :datetime
#

class Correspondence < ApplicationRecord
  attr_readonly :uuid

  validates :category,
            :topic, presence: true

  validates :name, presence: { message: "Full name can't be blank" }
  validates :email, presence: { message: "Email can't be blank" }
  validates :message, presence: { message: "Your message can't be blank" }

  validates :email, format: { with: /\A.*@.*\z/,
                              message: "Email is invalid",
                              if: proc { email.present? } }

  validates :category,
            inclusion: { in: Settings.correspondence_categories,
                         if: proc { category.present? } }
  validates :topic,
            length: { maximum: Settings.correspondence_topic_max_length }
  validates :message,
            length: { maximum: Settings.correspondence_message_max_length,
                      message: "Message is too long (maximum is 5000 characters)" }

  validates :contact_requested,
            inclusion: { in: %w[yes no],
                         if: proc { contact_requested.present? } }

  jsonb_accessor :content,
                 name: :string,
                 email: :string,
                 category: :string,
                 topic: :string,
                 message: :text,
                 contact_requested: :string

  before_validation :set_uuid, on: :create

  def topic_present?
    errors.add("topic", "What are you contacting the Ministry of Justice about? can't be blank") if topic.blank?
    topic.present?
  end

  def authenticated?
    !authenticated_at.nil?
  end

  def authenticate!
    unless authenticated?
      self.authenticated_at = Time.zone.now
      save!
    end
  end

  def confirmation_code
    @confirmation_code ||= uuid.split("-")[1, 2].join("-")
  end

  def self.all_by_message(message)
    where("content @> ?", { message: }.to_json)
  end

  def self.first_by_message(message)
    all_by_message(message).first
  end

private

  def set_uuid
    self.uuid = SecureRandom.uuid
  end
end

app/controllers/correspondence_controller.rb
class CorrespondenceController < ApplicationController
  rescue_from Redis::CannotConnectError do
    internal_server_error
  end

  def start; end

  def create
    creator = CorrespondenceCreator.new(correspondence_params)
    @correspondence = creator.correspondence
    case creator.result
    when :success
      redirect_to correspondence_confirmation_path(@correspondence.uuid)
    when :no_op
      redirect_to Settings.moj_home_page
    when :validation_error
      @search_api_client = GovUkSearchApi::Client.new(@correspondence.topic)
      @search_results = search_results(@search_api_client.search)
      render :search
    end
  end

  def confirmation
    @correspondence = Correspondence.find_by_uuid(params[:uuid])
  end

  def topic
    @correspondence = Correspondence.new
  end

  def search
    @correspondence = Correspondence.new(topic: search_params[:topic])
    if @correspondence.topic_present?
      @correspondence = Correspondence.new(topic: search_params[:topic])
      @search_api_client = GovUkSearchApi::Client.new(@correspondence.topic)
      @search_results = search_results(@search_api_client.search)
    else
      render :topic
    end
  end

  def authenticate
    @correspondence = Correspondence.where(uuid: params[:uuid]).first
    if @correspondence.nil?
      not_found and return
    elsif !@correspondence.authenticated?
      @correspondence.authenticate!
      CorrespondenceMailer.new_correspondence(@correspondence).deliver_later
    end
  end

  def t_and_c
    render
  end

private

  def category_attribute
    "general_enquiries"
  end

  def correspondence_params
    params.require(:correspondence).permit(
      :name,
      :email,
      :topic,
      :message,
      :contact_requested,
    ).merge({ category: category_attribute })
  end

  def search_params
    params.require(:correspondence).permit(:topic)
  end

  def search_results(search)
    results = search.result_items.each_with_index.map do |item, index|
      view_context.govuk_link_to(
        item.title,
        item.link,
        onclick: "ga('send', 'event', 'External Link - Results', '#{index + 1} - #{item.title} - #{item.link}')",
      )
    end

    results << view_context.govuk_link_to(
      t("correspondence.search.more_results"),
      @search_api_client.more_results_url,
      onclick: "ga('send', 'event', 'External Link - Results', '#{t('correspondence.search.more_results')}')",
    )

    results
  end
end

app/views/correspondence/_contact_form.html.erb
<div id="correspondence_contact_requested_yes_content" class=<%= local_assigns.fetch :klass, '' %>>
  <%= f.govuk_text_field :name %>
  <%= f.govuk_email_field :email %>
  <%= f.govuk_text_area :message, rows: 10, 'aria-labelledby': 'correspondence_message correspondence_message_count' %>

  <div class="char-counter form-group" data-maxlength=<%= Settings.correspondence_message_max_length %>>
     <p id="live-region-text" aria-live="polite">
       <span class="char-counter-count"><%= Settings.correspondence_message_max_length %></span>
       <%= " characters remaining" %>
    </p>
  </div>
  <p>
    <%= "By using this service you agree to these " %>
    <%= govuk_link_to "terms and conditions (opens in new tab)", correspondence_t_and_c_path, target: "_blank" %>
    <%= ". Please read them carefully." %>
  </p>

  <%= f.hidden_field :topic, value: @correspondence.topic %>
  <%= f.govuk_submit t('button.send'), class:'button', onclick: "ga('send', 'event', 'Question', 'Sent')" %>
</div>

app/views/correspondence/_feedback.html.erb
<%= t('.prompt') %>
<%= govuk_link_to t('.link'), t('.link_address') %>
<%= t('.time') %>

app/views/correspondence/about.html.slim
= render partial: 'layouts/header', locals: {page_heading: 'What is your question about?'}

= form_for @correspondence do |f|
  .no-legend
    = f.radio_button_fieldset :topic,
            choices: [:courts_and_tribunals, :prisons_and_probation, :something_else]
  = f.submit 'Continue', class: 'button'

app/views/correspondence/authenticate.html.erb
<% content_for :page_title, t('page_title.authentication_confirmation') %>
<%= render partial: 'layouts/header', locals: { page_heading: t('common.service_name')} %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <%= govuk_panel(text: t('.success')) %>

    <h2 class="govuk-heading-m"><%= t('.next_title') %></h2>
    <p><%= t('.we_will_reply') %></p>
    <p><%= t('.reply_timescale') %></p>

    <p>
      <%= render partial: 'feedback' %>
    </p>

    <p>
      <%= govuk_link_to t('button.moj_home'), Settings.moj_home_page %>
    </p>

  </div>
<div>

app/views/correspondence/confirmation.html.erb
<% content_for :page_title, t('page_title.contact_confirm') %>
<%= render partial: 'layouts/header', locals: { page_heading: t('.one_more_step') } %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <p><%= t('.next_copy_html', email: @correspondence.email) %></p>
  </div>
</div>

<div class="uuid" data-uuid="<%= @correspondence.uuid %>">
</div>

app/views/correspondence/search.html.erb
<% content_for :page_title, t('page_title.contact_form') %>
<%= render partial: 'layouts/header', locals: { page_heading: t('common.service_name')} %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h2 class="govuk-heading-m">You're contacting the Ministry of Justice about</h2>

    <p class="original-message"><%= @correspondence.topic %></p>

    <%= form_for @correspondence do |f| %>
      <%= f.govuk_error_summary %>

      <% if @search_results.size > 1 %>
        <h2 class="govuk-heading-l">The following information may help:</h2>
        <%= govuk_list @search_results, classes: "search-results" %>

        <%# i18n-tasks-use t('helpers.legend.correspondence.contact_requested') %>
        <%= f.govuk_radio_buttons_fieldset :contact_requested do %>
          <%= f.govuk_radio_button :contact_requested, 'yes', label: { text: "Yes" } %>
          <%= f.govuk_radio_button :contact_requested, 'no', label: { text: "No" } %>
        <% end %>
        <%= render partial: 'contact_form', locals: {f: f, klass: "js-hidden"} %>

        <p id="correspondence_contact_requested_no_content" class="js-hidden">
          <%= render partial: 'feedback' %>
        </p>
      <% else %>
        <%= render partial: 'contact_form', locals: {f: f} %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/correspondence/start.html.erb
<% content_for :page_title, t('page_title.start_page') %>
<%= render partial: 'layouts/header', locals: { page_heading: t('common.service_name') } %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <p class="govuk-body-l"><%= t('.service_hint') %></p>
    <p><%= t('.opening_paragraphs') %></p>

    <p class="govuk-body"><%= t('.reasons_heading') %>:</p>
    <%= govuk_list ["contains offensive or abusive language or material", "are repeated enquiries", "are selling or promoting a product"], type: :bullet %>

    <p>We are not able to provide legal advice.</p>
    <p>Write your message in English or Welsh.</p>
  </div>

  <div class="govuk-grid-column-one-third">
    <aside class="govuk-related-items">
      <h3 class="govuk-heading-m"><%= t('.other_services') %></h3>
      <%= govuk_list [
          govuk_link_to(t('.find_a_court_label'), t('.find_a_court_link'), onclick:"ga('send', 'event', 'External Link', '#{ t('.find_a_court_event')}')"),
          govuk_link_to(t('.find_a_prison_label'), t('.find_a_prison_link'), onclick:"ga('send', 'event', 'External Link', '#{ t('.find_a_prison_event')}')"),
          govuk_link_to(t('.visiting_a_prison_label'), t('.visiting_a_prison_link'), onclick:"ga('send', 'event', 'External Link', '#{ t('.visiting_a_prison_event')}')")
        ]
      %>
    </aside>
  </div>
</div>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <%= govuk_start_button(text: t('button.start'), href: correspondence_topic_path) %>
  </div>
</div>

app/views/correspondence/step_message.html.slim
= render partial: 'layouts/header', locals: {page_heading: 'About the Ministry of Justice'}

= form_for Correspondence.new do |f|

  = f.text_area :message

  = link_to "Continue", step_name_correspondence_index_path , {class: 'button'}

app/views/correspondence/step_name.html.slim
= render partial: 'layouts/header', locals: {page_heading: 'Your details'}

= form_for Correspondence.new do |f|

  = f.text_field :name

  = link_to "Continue", step_reply_correspondence_index_path , {class: 'button'}

app/views/correspondence/step_reply.html.slim
= render partial: 'layouts/header', locals: {page_heading: 'Your details'}

= form_for Correspondence.new do |f|

  = f.email_field :email

  = f.email_field :email_confirmation

  = link_to "Send", confirmation_correspondence_index_path , {class: 'button'}

app/views/correspondence/step_topic.html.slim
= render partial: 'layouts/header', locals: {page_heading: 'What is your question about?'}

= form_for @correspondence do |f|
  .no-legend
    = f.radio_button_fieldset :topic,
            choices: [:courts_and_tribunals, :prisons_and_probation, :something_else]
  = link_to "Continue", step_message_correspondence_index_path , {class: 'button'}

app/views/correspondence/t_and_c.html.erb
<% content_for :page_title, t('page_title.terms_and_conditions') %>
<%= render partial: 'layouts/header', locals: { page_heading: t('page_title.terms_and_conditions')} %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <p>By using this service you agree to these terms and conditions. Please read them carefully.</p>

    <h2 class="govuk-heading-m">Terms and conditions</h2>

    <h3 class="govuk-heading-s">General</h3>

    <p>These terms and conditions affect your rights and liabilities under the law. They govern your use of, and relationship with, the Ask aquestion service. They don’t apply to other services provided by the Ministry of Justice (MOJ), or to any other department or service which is linked to in this service.</p>
    <p>We may occasionally update these terms and conditions. This might happen if there’s a change in the law or to the way this service works. If there’s a change, you’ll be asked to agree to the new terms and conditions the next time you sign in, so you can continue to use this service.</p>
    <p>If you don’t agree to the terms and conditions set out in this document, you should not use this service to ask the MOJ a question.</p>

    <h3 class="govuk-heading-s">Applicable law</h3>
    <p>Your use of this service and any dispute arising from its use will be governed by and construed in accordance with the laws of England and Wales, including but not limited to the:</p>

    <%= govuk_list [
        "Freedom of Information Act 2000",
        "Computer Misuse Act 1990",
        "Mental Capacity Act 2005"
      ], type: "bullet"
    %>

    <h3 class="govuk-heading-s">How to use this service responsibly</h3>

    <p>There are risks in using a shared computer, such as in an internet café, to use this service. It’s your responsibility to be aware of these risks and to avoid using any computer which may leave your personal information accessible to others. You are responsible if you choose to leave a computer unprotected while asking a question.</p>
    <p>We make every effort to check and test this service whenever we amend or update it. However, you must take your own precautions to ensure that the way you access this service does not expose you to the risk of viruses, malicious computer code or other forms of interference which may damage your own computer system.</p>
    <p>You must not:</p>

    <%= govuk_list [
        "misuse our service by knowingly introducing viruses, trojans, worms, logic bombs or other material which is malicious or technologically harmful",
        "attempt to gain unauthorised access to our service, the system on which our service is stored or any server, computer or database connected to our service",
        "attack our site via a denial-of-service attack or a distributed denial-of-service attack"
      ], type: "bullet"
    %>

    <h2 class="govuk-heading-m">Privacy policy</h2>
    <p>This privacy policy explains why the Ministry of Justice collects personal data when you use the Ask a question service.</p>
    <p>The policy also explains:</p>

    <%= govuk_list [
        "how we store this data",
        "what we do with it",
        "how you can get a copy of the data we have about you",
        "how you can complain if you think we’ve done something wrong"
      ], type: "bullet"
    %>

    <p>This service is managed by the Ministry of Justice (MOJ). MOJ is the data controller for the personal information we hold.</p>
    <p>MOJ collects and processes personal data so that it can safely and securely provide answers to correspondence.</p>

    <h3 class="govuk-heading-s">About personal information</h3>
    <p>Personal data is information about you as an individual. It can be your name, address or telephone number.</p>
    <p>We know how important it is to protect your privacy and to comply with data protection laws. We will keep your personal data safe and will only disclose it where it is lawful to do so, or with your consent.</p>

    <h3 class="govuk-heading-s">Types of personal data we process</h3>
    <p>We only process personal data that is relevant for the services we are providing to you. This includes your question, query, feedback and email address. We also collect site-usage information which allows us to see how the service is being used in order to allow us to improve it. This information does not contain any personal data. It includes:</p>

    <%= govuk_list [
        "your IP address, and details of which version of web browser you used",
        "information on how you use the site, using cookies and page tagging techniques to help us improve the website"
      ], type: "bullet"
    %>

    <p>This helps us to:</p>
    <%= govuk_list [
        "improve the site by monitoring how you use it",
        "respond to any feedback you send us, if you’ve asked us to",
        "provide you with information about local services if you want it"
      ], type: "bullet"
    %>

    <p>We can’t personally identify you using your site usage data.</p>

    <h3 class="govuk-heading-s">Purpose of processing and the lawful basis for the process</h3>
    <p>We collect personal data to enable us to tailor and respond to your correspondence accordingly.</p>

    <h3 class="govuk-heading-s">Who the information may be shared with</h3>
    <p>We do not share your information with anyone else.</p>

    <h3 class="govuk-heading-s">Details of transfers to third country and safeguards</h3>
    <p>All data collected by this service is stored within the European Economic Area (EEA). However, due to the global nature of the internet, the data sent to and from the database may transit through countries outside of the EEA. Data is not stored in a non-EEA country. Any transfers made will be in full compliance with all aspects of the data protection law.</p>

    <h3 class="govuk-heading-s">How long we keep data</h3>
    <p>In the case of Freedom of Information (FOI) requests, data is retained for three years after the last action in accordance with FOI retention policy.</p>
    <p>In the case of Information Commissioner Reviews, data is destroyed after 5 years from last action.</p>
    <p>For all other requests, data is retained for two years after the last action.</p>

    <h3 class="govuk-heading-s">Access to personal information</h3>
    <p>You can find out if we hold any personal data about you by making a 'subject access request'. To make a subject access request please contact:</p>
    <p>
      <strong>Offender and ex-offenders;</strong>
      <br />
      Branston Registry
      <br />
      Building 16, S & T Store
      <br />
      Burton Road
      <br />
      Branston
      <br />
      Burton-on-Trent
      <br />
      Staffordshire
      <br />
      DE14 3EG
      <br />
    </p>
    <p>
      <strong>All others;</strong>
      <br />
      Disclosure Team
      <br />
      Post point 10.38
      <br />
      102 petty France
      <br />
      London
      <br />
      SW1H 9AJ
      <br />
    </p>

    <h3 class="govuk-heading-s">When we ask you for personal data</h3>
    <p>Whenever we ask for personal data, we promise to:</p>
    <%= govuk_list [
        "only ask for the information we need",
        "keep it safe and make sure nobody can access it unless authorised",
        "make sure we do not keep the data longer than needed",
        "only share the data with other organisations for legitimate purposes",
        "consider any request you make to correct, stop storing or delete your personal data"
      ], type: "bullet"
    %>

    <p>We also promise to make it easy for you to:</p>

    <%= govuk_list [
        "tell us at any time if you want us to stop storing your personal data",
        "make a complaint with the supervisory authority"
      ], type: "bullet"
    %>

    <h3 class="govuk-heading-s">More information</h3>
    <p>You can get more details on:</p>
    <%= govuk_list [
        "agreements we have with other organisations for sharing information",
        "when we can pass on personal information without telling you, for example, to help with the prevention or detection of crime or to produce anonymised statistics",
        "instructions we give to staff on how to collect, use or delete your personal information",
        "how we check that the information we hold is accurate and up-to-date",
        "how to make a complaint"
      ], type: "bullet"
    %>

    <p>For more information about the above issues, please contact:</p>
    <p>
      MoJ Data Protection Officer
      <br />
      Post point 10.38
      <br />
      102 petty France
      <br />
      London
      <br />
      SW1H 9AJ
      <br />
    </p>

    <p>
      or email:
      <a href="mailto:data.compliance@justice.gov.uk">data.compliance@justice.gov.uk</a>
    </p>
    <p>For more information on how and why your information is processed please see the information provided when you accessed our services or were contacted by us.</p>

    <h3 class="govuk-heading-s">Complaints</h3>
    <p>When we ask you for information, we will keep to the law. If you think that your information has been handled incorrectly, you can contact the Information Commissioner for independent advice about data protection at:</p>
    <p>
      Information Commissioner's Office
      <br />
      Wycliffe House
      <br />
      Water Lane
      <br />
      Wilmslow
      <br />
      Cheshire
      <br />
      SK9 5AF
      <br />
      Tel: 0303 123 1113
      <br />
      <a href="http://www.ico.org.uk"> www.ico.org.uk</a>
    </p>
  </div>
</div>

app/views/correspondence/topic.html.erb
<% content_for :page_title, t('page_title.topic_search') %>

<%= render partial: 'layouts/header', locals: { page_heading: t('common.service_name') } %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <p>
      <%= form_for @correspondence, url: correspondence_search_path, method: :get do |f| %>
        <%= f.govuk_error_summary %>
        <%= f.govuk_text_field :topic, maxlength: Settings.correspondence_topic_max_length %>
        <%= f.govuk_submit t('button.continue'), class:'button', onclick: "ga('send', 'event', 'Question', 'Search')" %>
      <% end %>
    </p>
  </div>
</div>